import { Analytics } from "@vercel/analytics/react";

export const metadata = {
  title: "Next.js",
  description: "Generated by Next.js",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <>
      <Analytics />
      <html lang="en">
        <body>{children}</body>
      </html>
    </>
  );
}
